"""add document extractions

Revision ID: 148ec5e37e4d
Revises: 66fc044033b8
Create Date: 2026-07-22 11:46:13.255420

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "148ec5e37e4d"
down_revision: Union[str, Sequence[str], None] = "66fc044033b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_extractions",
        sa.Column(
            "extraction_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "document_extractions",
        sa.Column(
            "validated_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_unique_constraint(
        "uq_document_extractions_document_id",
        "document_extractions",
        ["document_id"],
    )
    op.drop_column("document_extractions", "invoice_date")
    op.drop_column("document_extractions", "longitude")
    op.drop_column("document_extractions", "latitude")
    op.drop_column("document_extractions", "currency")
    op.drop_column("document_extractions", "supplier_address")
    op.drop_column("document_extractions", "total_amount")
    op.drop_column("document_extractions", "invoice_number")
    op.drop_column("document_extractions", "supplier_name")
    op.add_column(
        "documents", sa.Column("error_message", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "documents",
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "processed_at")
    op.drop_column("documents", "error_message")
    op.add_column(
        "document_extractions",
        sa.Column("supplier_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column("invoice_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column("total_amount", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column("supplier_address", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "document_extractions",
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "document_extractions",
        sa.Column("invoice_date", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "uq_document_extractions_document_id",
        "document_extractions",
        type_="unique",
    )
    op.alter_column(
        "document_extractions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("document_extractions", "validated_data")
    op.drop_column("document_extractions", "extraction_data")
    # ### end Alembic commands ###
